spring:
  #  datasource:
  #    url: jdbc:postgresql://127.0.0.1:5432/demo
  #    username: postgres
  #    password: postgres
  #    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
    redis:
      time-to-live: 360000 # 1 minute
  data:
    redis:
      host: ${REDIS_HOST:192.168.1.72}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:FDzBgj23V4in1jHP3VplBcTQQA6et6Ik}

#  cassandra:
#    port: 9042
#    keyspace-name: users
#    username: cassandra
#    password: cassandra
#    schema-action: create-if-not-exists #recreate_drop_unused
#    request:
#      timeout: 10s
#    connection:
#      connect-timeout: 10s
#      init-query-timeout: 10s
#    contact-points: mycasandra

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect